from django.test import TestCase
from django.contrib.auth.models import User
from challenges.models import Challenge, UserProgress
from challenges.levels import LEVELS
from certificates.models import UserCertificate
from challenges.services import ChallengeService


class CertificateFlowTest(TestCase):
    def setUp(self):
        self.user = User.objects.create_user(username="testuser", password="password")
        self.total_levels = len(LEVELS)
        # Create global challenges
        self.challenges = []
        for i in range(1, self.total_levels + 1):
            challenge = Challenge.objects.create(
                title=f"Level {i}",
                slug=f"level-{i}",
                description="test",
                initial_code="print('hello')",
                test_code="assert True",
                order=i,
                xp_reward=10,
            )
            self.challenges.append(challenge)

    def test_certificate_generation_on_final_level(self):
        # Complete all levels except final level.
        for challenge in self.challenges[:-1]:
            UserProgress.objects.create(
                user=self.user,
                challenge=challenge,
                status=UserProgress.Status.COMPLETED,
                stars=3,
            )

        completed = UserProgress.objects.filter(
            user=self.user,
            status=UserProgress.Status.COMPLETED,
        ).count()
        self.assertEqual(completed, self.total_levels - 1)

        # Submit final level.
        final_level = self.challenges[-1]

        result = ChallengeService.process_submission(
            self.user, final_level, passed=True
        )

        # Check result
        self.assertEqual(result["status"], "completed")

        # Certificate is auto-generated by post_save signal.
        self.assertTrue(UserCertificate.objects.filter(user=self.user).exists())
        cert = UserCertificate.objects.get(user=self.user)
        self.assertEqual(cert.completion_count, self.total_levels)

    def test_certificate_on_resubmission(self):
        # Complete all challenges first
        for challenge in self.challenges:
            UserProgress.objects.create(
                user=self.user,
                challenge=challenge,
                status=UserProgress.Status.COMPLETED,
                stars=3,
            )

        final_level = self.challenges[-1]

        # Submit final level again.
        result = ChallengeService.process_submission(
            self.user, final_level, passed=True
        )

        # Verify certificate is present on re-submission
        self.assertEqual(result["status"], "already_completed")
        self.assertTrue(UserCertificate.objects.filter(user=self.user).exists())

    def test_no_certificate_before_final_level(self):
        # Complete all levels except the final two.
        for challenge in self.challenges[:-2]:
            UserProgress.objects.create(
                user=self.user,
                challenge=challenge,
                status=UserProgress.Status.COMPLETED,
            )

        # Submit penultimate level.
        penultimate_level = self.challenges[-2]
        result = ChallengeService.process_submission(
            self.user, penultimate_level, passed=True
        )

        self.assertEqual(result["status"], "completed")
        self.assertFalse(UserCertificate.objects.filter(user=self.user).exists())
