# Generated by Django 5.0.9 on 2026-04-26 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["follower", "following"],
                        name="users_userf_followe_3f285f_idx",
                    ),
                    models.Index(
                        fields=["following", "follower"],
                        name="users_userf_followi_46a4eb_idx",
                    ),
                ],
                "unique_together": {("follower", "following")},
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("google", "Google"),
                            ("email", "Email OTP"),
                            ("local", "Local/Admin"),
                        ],
                        help_text="The OAuth provider used to create this account.",
                        max_length=20,
                    ),
                ),
                (
                    "provider_id",
                    models.CharField(
                        help_text="Unique ID returned by the OAuth provider (e.g., GitHub user ID).",
                        max_length=255,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="User's profile picture.",
                        null=True,
                        upload_to="avatars/",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        help_text="Profile background banner.",
                        null=True,
                        upload_to="banners/",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Short user biography.",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                (
                    "active_theme",
                    models.CharField(
                        default="vs-dark",
                        help_text="Active Monaco Editor theme.",
                        max_length=50,
                    ),
                ),
                (
                    "active_font",
                    models.CharField(
                        default="Fira Code",
                        help_text="Active Editor Font Family.",
                        max_length=50,
                    ),
                ),
                (
                    "active_effect",
                    models.CharField(
                        blank=True,
                        help_text="Active Cursor Effect (e.g., 'fire', 'particles').",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "active_victory",
                    models.CharField(
                        default="default",
                        help_text="Active Victory Animation.",
                        max_length=50,
                    ),
                ),
                (
                    "xp",
                    models.IntegerField(default=0, help_text="Total Experience Points earned."),
                ),
                (
                    "streak_freezes",
                    models.IntegerField(default=0, help_text="Number of streak freezes available."),
                ),
                (
                    "reward_cycle_start_date",
                    models.DateField(
                        blank=True,
                        help_text="Start date of the current 7-day reward cycle.",
                        null=True,
                    ),
                ),
                (
                    "referral_code",
                    models.CharField(
                        blank=True,
                        help_text="Unique code for inviting others.",
                        max_length=12,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who referred this account.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The associated Django User account.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "indexes": [
                    models.Index(fields=["-xp"], name="users_userp_xp_281062_idx"),
                    models.Index(fields=["provider"], name="users_userp_provide_930527_idx"),
                ],
                "unique_together": {("provider", "provider_id")},
            },
        ),
    ]
