# Generated by Django 6.0.1 on 2026-01-19 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="streak_freezes",
            field=models.IntegerField(
                default=0, help_text="Number of streak freezes available."
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                help_text="URL to user's profile picture.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="banner_url",
            field=models.URLField(
                blank=True,
                help_text="URL to profile background banner.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Short user biography.", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="provider",
            field=models.CharField(
                choices=[
                    ("github", "GitHub"),
                    ("google", "Google"),
                    ("discord", "Discord"),
                    ("local", "Local/Admin"),
                ],
                help_text="The OAuth provider used to create this account.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="provider_id",
            field=models.CharField(
                help_text="Unique ID returned by the OAuth provider (e.g., GitHub user ID).",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="referral_code",
            field=models.CharField(
                blank=True,
                help_text="Unique code for inviting others.",
                max_length=12,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who referred this account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                help_text="The associated Django User account.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="xp",
            field=models.IntegerField(
                default=0, help_text="Total Experience Points earned."
            ),
        ),
    ]
