# Generated by Django 6.0.1 on 2026-01-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_streak_freezes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="avatar_url",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="banner_url",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="User's profile picture.",
                null=True,
                upload_to="avatars/",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Profile background banner.",
                null=True,
                upload_to="banners/",
            ),
        ),
    ]
