# Generated by Django 6.0.1 on 2026-01-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_userprofile_reward_cycle_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="active_theme",
            field=models.CharField(
                default="vs-dark",
                help_text="Active Monaco Editor theme.",
                max_length=50,
            ),
        ),
    ]
