# Generated by Django 6.0.1 on 2026-01-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userprofile_active_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="active_effect",
            field=models.CharField(
                blank=True,
                help_text="Active Cursor Effect (e.g., 'fire', 'particles').",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="active_font",
            field=models.CharField(
                default="Fira Code",
                help_text="Active Editor Font Family.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="active_victory",
            field=models.CharField(
                default="default", help_text="Active Victory Animation.", max_length=50
            ),
        ),
    ]
