# Generated by Django 5.0.9 on 2026-02-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_userprofile_active_effect_userprofile_active_font_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="github_username",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="leetcode_username",
        ),
    ]
