# Generated by Django 5.0.9 on 2026-03-22 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_add_profile_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="userfollow",
            new_name="users_userf_followi_46a4eb_idx",
            old_name="users_userf_followi_1f0cff_idx",
        ),
        migrations.RenameIndex(
            model_name="userprofile",
            new_name="users_userp_xp_281062_idx",
            old_name="users_userp_xp_6f1f29_idx",
        ),
        migrations.RenameIndex(
            model_name="userprofile",
            new_name="users_userp_provide_930527_idx",
            old_name="users_userp_provide_5ca5fe_idx",
        ),
    ]
