# Generated by Django 5.0.9 on 2026-04-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0010_rename_users_userf_followi_1f0cff_idx_users_userf_followi_46a4eb_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="provider",
            field=models.CharField(
                choices=[
                    ("github", "GitHub"),
                    ("google", "Google"),
                    ("email", "Email OTP"),
                    ("local", "Local/Admin"),
                ],
                help_text="The OAuth provider used to create this account.",
                max_length=20,
            ),
        ),
    ]
