# Generated by Django 6.0.1 on 2026-01-21 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Markdown supported problem description"
                    ),
                ),
                (
                    "initial_code",
                    models.TextField(help_text="Starter code for the user"),
                ),
                (
                    "test_code",
                    models.TextField(
                        help_text="Hidden python code to assert the user solution"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order in the campaign level map"
                    ),
                ),
                ("xp_reward", models.IntegerField(default=50)),
                (
                    "time_limit",
                    models.IntegerField(
                        default=300, help_text="Suggested time in seconds for bonus"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Hint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "cost",
                    models.IntegerField(
                        default=10, help_text="XP cost to unlock this hint"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=1, help_text="Sequence of the hint"),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hints",
                        to="challenges.challenge",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("LOCKED", "Locked"),
                            ("UNLOCKED", "Unlocked"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="LOCKED",
                        max_length=20,
                    ),
                ),
                (
                    "stars",
                    models.IntegerField(
                        default=0, help_text="0-3 stars based on performance"
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="challenges.challenge",
                    ),
                ),
                (
                    "hints_unlocked",
                    models.ManyToManyField(
                        blank=True, related_name="unlocked_by", to="challenges.hint"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "challenge")},
            },
        ),
    ]
