# Generated by Django 5.0.9 on 2026-04-26 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    models.TextField(help_text="Markdown supported problem description"),
                ),
                (
                    "initial_code",
                    models.TextField(help_text="Starter code for the user"),
                ),
                (
                    "test_code",
                    models.TextField(help_text="Hidden python code to assert the user solution"),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Order in the campaign level map"),
                ),
                ("xp_reward", models.IntegerField(default=50)),
                (
                    "time_limit",
                    models.IntegerField(default=300, help_text="Suggested time in seconds for bonus"),
                ),
                (
                    "target_time_seconds",
                    models.IntegerField(
                        default=600,
                        help_text="Target completion time for 3-star rating (10 minutes default)",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="If false, only staff can see this challenge",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_for_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personalized_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("LOCKED", "Locked"),
                            ("UNLOCKED", "Unlocked"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="LOCKED",
                        max_length=20,
                    ),
                ),
                (
                    "stars",
                    models.IntegerField(default=0, help_text="0-3 stars based on performance"),
                ),
                (
                    "ai_hints_purchased",
                    models.IntegerField(
                        default=0,
                        help_text="Number of AI hints purchased for this level.",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When user first accessed this challenge",
                        null=True,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="challenges.challenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "status"], name="challenges__user_id_3f4dac_idx"),
                    models.Index(
                        fields=["user", "completed_at"],
                        name="challenges__user_id_f974df_idx",
                    ),
                    models.Index(
                        fields=["challenge", "status"],
                        name="challenges__challen_f309fd_idx",
                    ),
                ],
                "unique_together": {("user", "challenge")},
            },
        ),
    ]
