# Generated by Django 5.0.9 on 2026-02-03 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0004_challenge_created_for_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserCertificate",
        ),
    ]
