# Generated by Django 5.0.9 on 2026-02-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0005_delete_usercertificate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprogress",
            name="ai_assist_used",
        ),
        migrations.AddField(
            model_name="userprogress",
            name="ai_hints_purchased",
            field=models.IntegerField(
                default=0, help_text="Number of AI hints purchased for this level."
            ),
        ),
    ]
