# Generated by Django 5.0.9 on 2026-02-10 05:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0006_remove_userprogress_ai_assist_used_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("issued_date", models.DateTimeField(auto_now_add=True)),
                (
                    "certificate_image",
                    models.ImageField(blank=True, null=True, upload_to="certificates/"),
                ),
                ("is_valid", models.BooleanField(default=True)),
                (
                    "completion_count",
                    models.IntegerField(
                        default=49, help_text="Number of challenges completed"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_date"],
            },
        ),
    ]
