# Generated by Django 5.0.9 on 2026-02-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0008_remove_level_54"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprogress",
            name="hints_unlocked",
        ),
        migrations.AddField(
            model_name="challenge",
            name="target_time_seconds",
            field=models.IntegerField(
                default=600,
                help_text="Target completion time for 3-star rating (10 minutes default)",
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When user first accessed this challenge",
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Hint",
        ),
    ]
