# Generated by Django 5.0.9 on 2026-02-16 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0009_remove_userprogress_hints_unlocked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="category",
            field=models.CharField(
                choices=[
                    ("basics", "Basics"),
                    ("strings", "Strings"),
                    ("lists", "Lists & Tuples"),
                    ("dicts", "Dictionaries & Sets"),
                    ("control-flow", "Control Flow"),
                    ("functions", "Functions"),
                    ("oop", "Object-Oriented Programming"),
                    ("modules", "Modules & Exceptions"),
                ],
                default="basics",
                help_text="Problem category/domain",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="easy",
                help_text="Problem difficulty level",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="test_code",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Legacy: Hidden python assert code (deprecated, use TestCase model)",
            ),
        ),
        migrations.AlterField(
            model_name="usercertificate",
            name="completion_count",
            field=models.IntegerField(
                help_text="Number of challenges completed when certificate was issued"
            ),
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_data",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Stdin input for this test case",
                    ),
                ),
                (
                    "expected_output",
                    models.TextField(help_text="Expected stdout output"),
                ),
                (
                    "is_sample",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this test case is visible to the user as a sample",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="challenges.challenge",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
