# Generated by Django 5.0.9 on 2026-02-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0010_challenge_category_challenge_difficulty_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="category",
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="difficulty",
        ),
        migrations.AlterField(
            model_name="challenge",
            name="test_code",
            field=models.TextField(
                help_text="Hidden python code to assert the user solution"
            ),
        ),
        migrations.DeleteModel(
            name="TestCase",
        ),
    ]
