# Generated by Django 5.0.9 on 2026-03-22 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0013_add_progress_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="userprogress",
            new_name="challenges__user_id_3f4dac_idx",
            old_name="challenge_u_user_id_047eb8_idx",
        ),
        migrations.RenameIndex(
            model_name="userprogress",
            new_name="challenges__user_id_f974df_idx",
            old_name="challenge_u_user_id_70eb0f_idx",
        ),
        migrations.RenameIndex(
            model_name="userprogress",
            new_name="challenges__challen_f309fd_idx",
            old_name="challenge_u_challen_7805a8_idx",
        ),
    ]
