# Generated by Django 5.0.9 on 2026-04-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0014_rename_challenge_u_user_id_047eb8_idx_challenges__user_id_3f4dac_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="is_published",
            field=models.BooleanField(
                default=True, help_text="If false, only staff can see this challenge"
            ),
        ),
    ]
