"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _buy_xp_page from './buy-xp-page.bones.json'
import _home_page from './home-page.bones.json'
import _landing_page from './landing-page.bones.json'
import _login_page from './login-page.bones.json'

registerBones({
  "buy-xp-page": _buy_xp_page,
  "home-page": _home_page,
  "landing-page": _landing_page,
  "login-page": _login_page,
})
