import logging
import os

import requests
from django.http import StreamingHttpResponse

from authentication.throttles import CodeExecutionRateThrottle
from celery.result import AsyncResult
from challenges.models import Challenge, UserProgress
from challenges.serializers import (
    AIAnalysisRequestSerializer,
    AIAssistPurchaseResponseSerializer,
    AIHintRequestSerializer,
    AITaskStatusResponseSerializer,
    ChallengeAdminSerializer,
    ChallengeContextResponseSerializer,
    ChallengeExecuteRequestSerializer,
    ChallengePublicSerializer,
    ChallengeSubmissionRequestSerializer,
)
from challenges.services import ChallengeService
from django.core.cache import cache
from drf_spectacular.utils import OpenApiTypes, extend_schema
from project.internal_auth import authorize_internal_request
from rest_framework import decorators, status, viewsets
from rest_framework.permissions import AllowAny, IsAdminUser, IsAuthenticated
from rest_framework.response import Response

from ..tasks import (
    execute_code_task,
    generate_ai_analysis_task,
    generate_ai_hint_task,
    submit_code_task,
)
from .base import (
    _analysis_cache_key,
    _build_ai_result_response,
    _store_ai_task_meta,
    _task_meta_cache_key,
    _task_status_label,
)

logger = logging.getLogger(__name__)


class ChallengeViewSet(viewsets.ModelViewSet):
    """
    ViewSet for Challenge model.
    Provides read-only access for published challenges and administrative CRUD for staff.
    """

    lookup_field = "slug"

    def get_queryset(self):
        """Filters challenges based on publication status and user permissions."""
        if self.request.user.is_staff:
            return Challenge.objects.all().order_by("order")
        return Challenge.objects.filter(is_published=True).order_by("order")

    def get_serializer_class(self):
        """Returns appropriate serializer based on user role."""
        if self.request.user.is_staff:
            return ChallengeAdminSerializer
        return ChallengePublicSerializer

    def get_permissions(self):
        """Maps actions to specific permission classes."""
        user_actions = [
            "list",
            "retrieve",
            "submit",
            "execute",
            "purchase_ai_assist",
            "ai_hint",
            "ai_hint_stream",
            "ai_analyze",
            "task_status",
        ]
        internal_actions = ["internal_context", "internal_list"]

        if self.action in internal_actions:
            return [AllowAny()]
        if self.action in user_actions:
            return [IsAuthenticated()]
        return [IsAdminUser()]

    def get_object(self):
        """
        Overrides default lookup to support slug, numeric ID, or campaign order.
        Priority: Slug > Order (if numeric) > ID (if numeric).
        """
        lookup_value = self.kwargs[self.lookup_field]
        queryset = self.get_queryset()

        # 1. Try Slug
        obj = queryset.filter(slug=lookup_value).first()
        if obj:
            return obj

        # 2. Try Order or ID if numeric
        if lookup_value.isdigit():
            val = int(lookup_value)
            obj = queryset.filter(order=val).first() or queryset.filter(id=val).first()
            if obj:
                return obj

        from django.shortcuts import get_object_or_404

        return get_object_or_404(queryset, slug=lookup_value)

    @extend_schema(
        responses={200: ChallengePublicSerializer(many=True)},
        description="List all available challenges with annotated user-specific progress status.",
    )
    def list(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        annotated_queryset = ChallengeService.get_annotated_challenges(request.user, queryset)

        # We manually serialize to include the annotated fields (user_status, user_stars)
        # as they are not part of the base model but generated by the service.
        data = []
        for item in annotated_queryset:
            serializer = self.get_serializer(item)
            challenge_data = serializer.data
            challenge_data["status"] = getattr(item, "user_status", "LOCKED")
            challenge_data["stars"] = getattr(item, "user_stars", 0)
            data.append(challenge_data)

        return Response(data, status=status.HTTP_200_OK)

    @extend_schema(
        responses={200: ChallengePublicSerializer},
        description="Retrieve full details for a challenge including user progress and purchase status.",
    )
    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        serializer = self.get_serializer(instance)
        data = serializer.data

        # Augment with dynamic user-specific details
        details = ChallengeService.get_challenge_details(request.user, instance)
        data.update(
            {
                "status": details["status"],
                "stars": details["stars"],
                "ai_hints_purchased": details["ai_hints_purchased"],
                "started_at": (details["started_at"].isoformat() if details["started_at"] else None),
            }
        )

        return Response(data, status=status.HTTP_200_OK)

    @extend_schema(
        request=ChallengeSubmissionRequestSerializer,
        responses={202: OpenApiTypes.OBJECT},
        description="Submit code for validation. Returns a task_id for tracking the execution result.",
    )
    @decorators.action(detail=True, methods=["post"], throttle_classes=[CodeExecutionRateThrottle])
    def submit(self, request, slug=None):
        challenge = self.get_object()
        user_code = request.data.get("code")

        if not user_code or not str(user_code).strip():
            return Response(
                {"error": "Code content is required."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        task = submit_code_task.delay(request.user.id, challenge.id, user_code)

        if task.ready():
            try:
                res = task.get()
                return _build_ai_result_response(res)
            except Exception as e:
                return Response({"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

        return Response({"status": "pending", "task_id": task.id}, status=status.HTTP_202_ACCEPTED)

    @extend_schema(
        request=ChallengeExecuteRequestSerializer,
        responses={202: OpenApiTypes.OBJECT},
        description="Run code against challenge test cases in trial mode (no submission).",
    )
    @decorators.action(detail=True, methods=["post"], throttle_classes=[CodeExecutionRateThrottle])
    def execute(self, request, slug=None):
        challenge = self.get_object()
        user_code = request.data.get("code", "")

        task = execute_code_task.delay(request.user.id, challenge.id, user_code)

        if task.ready():
            try:
                res = task.get()
                return _build_ai_result_response(res)
            except Exception as e:
                return Response({"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

        return Response({"status": "pending", "task_id": task.id}, status=status.HTTP_202_ACCEPTED)

    @extend_schema(
        request=None,
        responses={
            200: AIAssistPurchaseResponseSerializer,
            400: OpenApiTypes.OBJECT,
            402: OpenApiTypes.OBJECT,
        },
        description="Deduct XP to unlock the next level of AI assistance for this challenge.",
    )
    @decorators.action(detail=True, methods=["post"])
    def purchase_ai_assist(self, request, slug=None):
        challenge = self.get_object()
        try:
            remaining_xp = ChallengeService.purchase_ai_assist(request.user, challenge)
            progress, _ = UserProgress.objects.get_or_create(user=request.user, challenge=challenge)

            return Response(
                {
                    "status": "purchased",
                    "remaining_xp": remaining_xp,
                    "hints_purchased": progress.ai_hints_purchased,
                    "message": "AI assistance level upgraded successfully.",
                },
                status=status.HTTP_200_OK,
            )
        except PermissionError as e:
            # Check if it was insufficient XP or max hints
            if "Maximum" in str(e):
                return Response({"error": str(e)}, status=status.HTTP_400_BAD_REQUEST)
            return Response({"error": str(e)}, status=status.HTTP_402_PAYMENT_REQUIRED)

    @extend_schema(
        request=AIHintRequestSerializer,
        responses={202: OpenApiTypes.OBJECT, 402: OpenApiTypes.OBJECT},
        description="Request an AI-generated hint. Requires corresponding assistance level to be purchased.",
    )
    @decorators.action(detail=True, methods=["post"], url_path="ai-hint")
    def ai_hint(self, request, slug=None):
        challenge = self.get_object()
        user = request.user
        progress, _ = UserProgress.objects.get_or_create(user=user, challenge=challenge)

        try:
            hint_level = int(request.data.get("hint_level", 1))
            if not (1 <= hint_level <= 3):
                return Response(
                    {"error": "hint_level must be between 1 and 3."},
                    status=status.HTTP_400_BAD_REQUEST,
                )
        except (TypeError, ValueError):
            return Response(
                {"error": "hint_level must be an integer."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        if progress.ai_hints_purchased < hint_level:
            return Response(
                {"error": f"AI Hint Level {hint_level} is not yet purchased."},
                status=status.HTTP_402_PAYMENT_REQUIRED,
            )

        # Check cache for existing hint to save AI tokens
        cache_key = f"ai_hint:{user.id}:{challenge.id}:level:{hint_level}"
        cached_hint = cache.get(cache_key)
        if cached_hint:
            return Response(
                {"hint": cached_hint, "hint_level": hint_level, "cached": True},
                status=status.HTTP_200_OK,
            )

        async_result = generate_ai_hint_task.delay(
            user_id=user.id,
            challenge_id=challenge.id,
            challenge_slug=challenge.slug,
            user_code=request.data.get("user_code", ""),
            hint_level=hint_level,
            user_xp=user.profile.xp,
        )
        _store_ai_task_meta(async_result.id, user.id, "hint")

        if async_result.ready():
            try:
                result = async_result.get()
                return _build_ai_result_response(result)
            except Exception as e:
                return Response(
                    {"status": "failed", "error": str(e)},
                    status=status.HTTP_500_INTERNAL_SERVER_ERROR,
                )

        return Response(
            {"task_id": async_result.id, "status": "queued"},
            status=status.HTTP_202_ACCEPTED,
        )

    @extend_schema(
        request=AIHintRequestSerializer,
        responses={200: OpenApiTypes.STR, 402: OpenApiTypes.OBJECT},
        description="INTERNAL PROXY: Request a streaming AI hint. Requires assistance level to be purchased.",
    )
    @decorators.action(detail=True, methods=["post"], url_path="ai-hint-stream")
    def ai_hint_stream(self, request, slug=None):
        challenge = self.get_object()
        user = request.user
        progress, _ = UserProgress.objects.get_or_create(user=user, challenge=challenge)

        try:
            hint_level = int(request.data.get("hint_level", 1))
        except (TypeError, ValueError):
            return Response({"error": "hint_level must be an integer."}, status=status.HTTP_400_BAD_REQUEST)

        if progress.ai_hints_purchased < hint_level:
            return Response(
                {"error": f"AI Hint Level {hint_level} is not yet purchased."},
                status=status.HTTP_402_PAYMENT_REQUIRED,
            )

        ai_url = os.getenv("AI_SERVICE_URL", "http://ai:8002")
        headers = _build_internal_headers("/hints/stream")
        payload = {
            "user_code": request.data.get("user_code", ""),
            "challenge_slug": challenge.slug,
            "hint_level": hint_level,
            "user_xp": user.profile.xp,
        }

        def stream_generator():
            try:
                # Proxy the request to the AI service with internal auth headers
                with requests.post(
                    f"{ai_url}/hints/stream",
                    json=payload,
                    headers=headers,
                    stream=True,
                    timeout=60
                ) as r:
                    r.raise_for_status()
                    for chunk in r.iter_content(chunk_size=None):
                        if chunk:
                            yield chunk
            except Exception as e:
                logger.error(f"AI hint streaming proxy failed: {e}")
                yield f"data: Error in AI proxy: {str(e)}\n\n".encode("utf-8")

        return StreamingHttpResponse(stream_generator(), content_type="text/event-stream")

    @extend_schema(
        request=AIAnalysisRequestSerializer,
        responses={202: OpenApiTypes.OBJECT},
        description="Request deep AI analysis and feedback for the current code implementation.",
    )
    @decorators.action(detail=True, methods=["post"], url_path="ai-analyze")
    def ai_analyze(self, request, slug=None):
        challenge = self.get_object()
        user_code = request.data.get("user_code", "")

        # Check cache for identical code to avoid redundant AI calls
        cache_key = _analysis_cache_key(challenge.id, user_code)
        cached_analysis = cache.get(cache_key)
        if cached_analysis:
            return Response({**cached_analysis, "cached": True}, status=status.HTTP_200_OK)

        async_result = generate_ai_analysis_task.delay(
            user_id=request.user.id,
            challenge_id=challenge.id,
            challenge_slug=challenge.slug,
            user_code=user_code,
        )
        _store_ai_task_meta(async_result.id, request.user.id, "analysis")

        return Response(
            {"task_id": async_result.id, "status": "queued"},
            status=status.HTTP_202_ACCEPTED,
        )

    @extend_schema(
        responses={200: AITaskStatusResponseSerializer, 404: OpenApiTypes.OBJECT},
        description="Poll for the status and result of an asynchronous AI task.",
    )
    @decorators.action(detail=False, methods=["get"], url_path=r"tasks/(?P<task_id>[^/.]+)/status")
    def task_status(self, request, task_id=None):
        task_meta = cache.get(_task_meta_cache_key(task_id)) or {}
        if task_meta.get("user_id") != request.user.id:
            return Response(
                {"error": "Task context not found or access denied."},
                status=status.HTTP_404_NOT_FOUND,
            )

        async_result = AsyncResult(task_id)
        response_data = {
            "task_id": task_id,
            "status": _task_status_label(async_result),
            "date_done": (str(async_result.date_done) if async_result.date_done else None),
        }

        if not async_result.ready():
            return Response(response_data, status=status.HTTP_200_OK)

        # Process result if ready
        task_result = async_result.result
        if async_result.successful() and isinstance(task_result, dict) and task_result.get("ok"):
            response_data["result"] = task_result.get("payload", {})
        else:
            response_data["error"] = (
                task_result.get("error", "AI generation failed.") if isinstance(task_result, dict) else str(task_result)
            )

        return Response(response_data, status=status.HTTP_200_OK)

    @extend_schema(
        responses={
            200: ChallengeContextResponseSerializer,
            403: OpenApiTypes.OBJECT,
            404: OpenApiTypes.OBJECT,
        },
        description="INTERNAL: Retrieve full challenge context (includes hidden test code). Protected by API key.",
    )
    @decorators.action(detail=True, methods=["get"], url_path="context")
    def internal_context(self, request, slug=None):
        if not authorize_internal_request(request):
            return Response(
                {"error": "Unauthorized internal request."},
                status=status.HTTP_403_FORBIDDEN,
            )

        challenge = self.get_object()
        return Response(
            {
                "challenge_title": challenge.title,
                "description": challenge.description,
                "initial_code": challenge.initial_code,
                "test_code": challenge.test_code,
            },
            status=status.HTTP_200_OK,
        )

    @extend_schema(
        responses={200: ChallengeContextResponseSerializer(many=True)},
        description="INTERNAL: List all challenges with full context. Protected by API key.",
    )
    @decorators.action(detail=False, methods=["get"], url_path="internal-list")
    def internal_list(self, request):
        if not authorize_internal_request(request):
            return Response(
                {"error": "Unauthorized internal request."},
                status=status.HTTP_403_FORBIDDEN,
            )

        queryset = Challenge.objects.all().order_by("order")
        data = []
        for challenge in queryset:
            data.append(
                {
                    "slug": challenge.slug,
                    "challenge_title": challenge.title,
                    "description": challenge.description,
                    "initial_code": challenge.initial_code,
                    "test_code": challenge.test_code,
                }
            )
        return Response(data, status=status.HTTP_200_OK)
