def desc(problem, input_format, output_format, example, constraints):
    return (
        "### Problem Statement\n"
        f"{problem}\n\n"
        "### Input Format\n"
        f"{input_format}\n\n"
        "### Output Format\n"
        f"{output_format}\n\n"
        "### Example\n"
        f"{example}\n\n"
        "### Constraints\n"
        f"{constraints}"
    )


def level(
    order,
    title,
    problem,
    input_format,
    output_format,
    example,
    constraints,
    initial_code,
    test_code,
    target_time_seconds,
):
    return {
        "title": title,
        "slug": f"python-{order:03d}",
        "description": desc(
            problem=problem,
            input_format=input_format,
            output_format=output_format,
            example=example,
            constraints=constraints,
        ),
        "initial_code": initial_code,
        "test_code": test_code,
        "order": order,
        "xp_reward": order * 10,
        "target_time_seconds": target_time_seconds,
    }


LEVELS = [
    # STAGE 1: PYTHON BASICS (1-10)
    level(
        1,
        "Hello Function",
        'Create `say_hello()` that returns the exact string `"Hello, Python!"`.',
        "`say_hello()` takes no arguments.",
        "Return the greeting string exactly.",
        '`say_hello()` -> `"Hello, Python!"`',
        "- Return, do not print.\n- Keep punctuation exact.",
        "def say_hello():\n    pass\n",
        'assert say_hello() == "Hello, Python!"\nassert isinstance(say_hello(), str)',
        120,
    ),
    level(
        2,
        "Add Ten",
        "Implement `add_ten(n)` that adds 10 to an integer.",
        "`n` is an integer.",
        "Return `n + 10`.",
        "`add_ten(7)` -> `17`",
        "- Handle negative, zero, and positive values.",
        "def add_ten(n):\n    pass\n",
        "assert add_ten(7) == 17\nassert add_ten(-10) == 0\nassert add_ten(0) == 10",
        120,
    ),
    level(
        3,
        "Multiply Two Numbers",
        "Write `multiply(a, b)` to return the product of two numbers.",
        "`a` and `b` are integers.",
        "Return `a * b`.",
        "`multiply(3, 4)` -> `12`",
        "- Use arithmetic operators only.",
        "def multiply(a, b):\n    pass\n",
        "assert multiply(3, 4) == 12\nassert multiply(-2, 5) == -10\nassert multiply(0, 99) == 0",
        120,
    ),
    level(
        4,
        "Count Characters",
        "Implement `count_chars(text)` that returns the length of a string.",
        "`text` is a string.",
        "Return the number of characters.",
        '`count_chars("code")` -> `4`',
        "- Spaces count as characters.",
        "def count_chars(text):\n    pass\n",
        'assert count_chars("code") == 4\nassert count_chars("") == 0\nassert count_chars("a b") == 3',
        120,
    ),
    level(
        5,
        "Even Check",
        "Create `is_even(n)` that returns whether `n` is even.",
        "`n` is an integer.",
        "Return `True` when `n` is even, else `False`.",
        "`is_even(8)` -> `True`",
        "- Return a boolean value.",
        "def is_even(n):\n    pass\n",
        "assert is_even(8) is True\nassert is_even(9) is False\nassert is_even(0) is True",
        150,
    ),
    level(
        6,
        "Celsius To Fahrenheit",
        "Write `celsius_to_fahrenheit(c)` using the formula `(c * 9/5) + 32`.",
        "`c` is a number (int or float).",
        "Return temperature in Fahrenheit.",
        "`celsius_to_fahrenheit(0)` -> `32.0`",
        "- Return a numeric value.",
        "def celsius_to_fahrenheit(c):\n    pass\n",
        "assert celsius_to_fahrenheit(0) == 32\nassert celsius_to_fahrenheit(100) == 212\nassert celsius_to_fahrenheit(-40) == -40",
        150,
    ),
    level(
        7,
        "Non Negative",
        "Implement `non_negative(n)`.\nIf `n` is negative, return `0`; otherwise return `n`.",
        "`n` is an integer.",
        "Return an integer.",
        "`non_negative(-3)` -> `0`",
        "- Preserve non-negative input values.",
        "def non_negative(n):\n    pass\n",
        "assert non_negative(-3) == 0\nassert non_negative(6) == 6\nassert non_negative(0) == 0",
        150,
    ),
    level(
        8,
        "Normalize Username",
        "Create `normalize_username(name)` that trims spaces and lowercases the value.",
        "`name` is a string.",
        "Return normalized username.",
        '`normalize_username("  Kira_01  ")` -> `"kira_01"`',
        "- Use string methods only.",
        "def normalize_username(name):\n    pass\n",
        'assert normalize_username("  Kira_01  ") == "kira_01"\nassert normalize_username("USER") == "user"',
        150,
    ),
    level(
        9,
        "Swap Pair",
        "Write `swap_pair(a, b)` that returns values in reverse order.",
        "`a` and `b` can be any values.",
        "Return `(b, a)` as a tuple.",
        "`swap_pair(1, 2)` -> `(2, 1)`",
        "- Return a tuple of length 2.",
        "def swap_pair(a, b):\n    pass\n",
        'assert swap_pair(1, 2) == (2, 1)\nassert swap_pair("x", "y") == ("y", "x")',
        180,
    ),
    level(
        10,
        "Rectangle Area",
        "Implement `rectangle_area(width, height)`.",
        "`width` and `height` are non-negative numbers.",
        "Return area `width * height`.",
        "`rectangle_area(5, 3)` -> `15`",
        "- Return `0` when one side is `0`.",
        "def rectangle_area(width, height):\n    pass\n",
        "assert rectangle_area(5, 3) == 15\nassert rectangle_area(0, 7) == 0\nassert rectangle_area(2.5, 4) == 10.0",
        180,
    ),
    # STAGE 2: DATA STRUCTURES (11-20)
    level(
        11,
        "First Item",
        "Create `first_item(items)` that returns the first list element.\nReturn `None` when the list is empty.",
        "`items` is a list.",
        "Return first value or `None`.",
        "`first_item([4, 5, 6])` -> `4`",
        "- Do not modify the list.",
        "def first_item(items):\n    pass\n",
        'assert first_item([4, 5, 6]) == 4\nassert first_item(["a"]) == "a"\nassert first_item([]) is None',
        180,
    ),
    level(
        12,
        "Last Item",
        "Implement `last_item(items)`.\nReturn `None` when empty.",
        "`items` is a list.",
        "Return final element or `None`.",
        "`last_item([1, 2, 3])` -> `3`",
        "- Use index-based access.",
        "def last_item(items):\n    pass\n",
        'assert last_item([1, 2, 3]) == 3\nassert last_item(["z"]) == "z"\nassert last_item([]) is None',
        180,
    ),
    level(
        13,
        "Sum List",
        "Write `sum_list(nums)` to return the sum of all list values.",
        "`nums` is a list of integers.",
        "Return an integer sum.",
        "`sum_list([2, 3, 4])` -> `9`",
        "- Empty list should return `0`.",
        "def sum_list(nums):\n    pass\n",
        "assert sum_list([2, 3, 4]) == 9\nassert sum_list([]) == 0\nassert sum_list([-2, 5, -1]) == 2",
        180,
    ),
    level(
        14,
        "Max Value",
        "Implement `max_list(nums)` to return the maximum value in a non-empty list.",
        "`nums` is a non-empty list of integers.",
        "Return the largest value.",
        "`max_list([7, 2, 9])` -> `9`",
        "- Assume list has at least one item.",
        "def max_list(nums):\n    pass\n",
        "assert max_list([7, 2, 9]) == 9\nassert max_list([-3, -1, -8]) == -1",
        180,
    ),
    level(
        15,
        "Reverse Copy",
        "Create `reverse_copy(items)` that returns a new reversed list.",
        "`items` is a list.",
        "Return reversed list.",
        "`reverse_copy([1, 2, 3])` -> `[3, 2, 1]`",
        "- Do not mutate the input list.",
        "def reverse_copy(items):\n    pass\n",
        "src = [1, 2, 3]\nout = reverse_copy(src)\nassert out == [3, 2, 1]\nassert src == [1, 2, 3]",
        210,
    ),
    level(
        16,
        "Count Occurrences",
        "Write `count_occurrences(items, target)` that counts how many times `target` appears.",
        "`items` is a list.",
        "Return occurrence count as integer.",
        "`count_occurrences([1,2,1], 1)` -> `2`",
        "- Return `0` if target is not present.",
        "def count_occurrences(items, target):\n    pass\n",
        'assert count_occurrences([1, 2, 1, 1], 1) == 3\nassert count_occurrences(["a", "b"], "x") == 0',
        210,
    ),
    level(
        17,
        "Unique In Order",
        "Implement `unique_in_order(items)` to remove duplicates while preserving first appearance order.",
        "`items` is a list.",
        "Return a new list with unique values in original order.",
        "`unique_in_order([1,2,1,3,2])` -> `[1,2,3]`",
        "- Preserve order.",
        "def unique_in_order(items):\n    pass\n",
        "assert unique_in_order([1, 2, 1, 3, 2]) == [1, 2, 3]\nassert unique_in_order([]) == []",
        210,
    ),
    level(
        18,
        "Merge Scoreboards",
        "Build `merge_scoreboards(left, right)`.\nBoth are dictionaries with integer values. Sum values for matching keys.",
        "`left` and `right` are dictionaries of `{str: int}`.",
        "Return merged dictionary.",
        "`{'a':2} + {'a':3,'b':1}` -> `{'a':5,'b':1}`",
        "- Include all keys from both dictionaries.",
        "def merge_scoreboards(left, right):\n    pass\n",
        "assert merge_scoreboards({'a': 2}, {'a': 3, 'b': 1}) == {'a': 5, 'b': 1}\nassert merge_scoreboards({}, {'x': 4}) == {'x': 4}",
        210,
    ),
    level(
        19,
        "Index Words",
        "Implement `index_words(words)` that maps each word to its first index.",
        "`words` is a list of strings.",
        "Return dictionary `{word: first_index}`.",
        "`index_words(['a','b','a'])` -> `{'a':0,'b':1}`",
        "- Keep first occurrence index.",
        "def index_words(words):\n    pass\n",
        "assert index_words(['a', 'b', 'a']) == {'a': 0, 'b': 1}\nassert index_words([]) == {}",
        240,
    ),
    level(
        20,
        "Flatten One Level",
        "Write `flatten_once(rows)` to flatten a 2D list by one level.",
        "`rows` is a list of lists.",
        "Return a single flat list.",
        "`flatten_once([[1,2],[3]])` -> `[1,2,3]`",
        "- Only flatten one nesting level.",
        "def flatten_once(rows):\n    pass\n",
        "assert flatten_once([[1, 2], [3]]) == [1, 2, 3]\nassert flatten_once([[], [4, 5]]) == [4, 5]",
        240,
    ),
    # STAGE 3: CONTROL FLOW (21-30)
    level(
        21,
        "Sign Label",
        "Create `sign_label(n)` that returns `'positive'`, `'negative'`, or `'zero'`.",
        "`n` is an integer.",
        "Return one of the three labels.",
        "`sign_label(-2)` -> `'negative'`",
        "- Match labels exactly.",
        "def sign_label(n):\n    pass\n",
        "assert sign_label(8) == 'positive'\nassert sign_label(-2) == 'negative'\nassert sign_label(0) == 'zero'",
        240,
    ),
    level(
        22,
        "Grade Band",
        "Implement `grade_from_score(score)` using:\nA: 90-100, B: 80-89, C: 70-79, D: 60-69, F: below 60.",
        "`score` is an integer 0..100.",
        "Return one letter grade.",
        "`grade_from_score(84)` -> `'B'`",
        "- Return uppercase letters only.",
        "def grade_from_score(score):\n    pass\n",
        "assert grade_from_score(97) == 'A'\nassert grade_from_score(84) == 'B'\nassert grade_from_score(72) == 'C'\nassert grade_from_score(61) == 'D'\nassert grade_from_score(12) == 'F'",
        240,
    ),
    level(
        23,
        "Leap Year",
        "Write `is_leap_year(year)`.\nA year is leap if divisible by 4, except centuries unless divisible by 400.",
        "`year` is an integer.",
        "Return `True`/`False`.",
        "`is_leap_year(2000)` -> `True`",
        "- Implement full Gregorian rule.",
        "def is_leap_year(year):\n    pass\n",
        "assert is_leap_year(2000) is True\nassert is_leap_year(1900) is False\nassert is_leap_year(2024) is True\nassert is_leap_year(2023) is False",
        270,
    ),
    level(
        24,
        "Factorial",
        "Implement `factorial(n)` iteratively.",
        "`n` is an integer where `n >= 0`.",
        "Return `n!`.",
        "`factorial(5)` -> `120`",
        "- `factorial(0)` must return `1`.",
        "def factorial(n):\n    pass\n",
        "assert factorial(0) == 1\nassert factorial(1) == 1\nassert factorial(5) == 120\nassert factorial(7) == 5040",
        270,
    ),
    level(
        25,
        "Count Vowels",
        "Create `count_vowels(text)` that counts vowels in a string.",
        "`text` is a string.",
        "Return count of `a,e,i,o,u` ignoring case.",
        "`count_vowels('Code')` -> `2`",
        "- Only English vowels.",
        "def count_vowels(text):\n    pass\n",
        "assert count_vowels('Code') == 2\nassert count_vowels('PYTHON') == 1\nassert count_vowels('rhythm') == 0",
        270,
    ),
    level(
        26,
        "Divisors",
        "Write `divisors(n)` that returns all positive divisors of `n` in ascending order.",
        "`n` is an integer and `n > 0`.",
        "Return list of divisors.",
        "`divisors(12)` -> `[1,2,3,4,6,12]`",
        "- Include `1` and `n`.",
        "def divisors(n):\n    pass\n",
        "assert divisors(1) == [1]\nassert divisors(12) == [1, 2, 3, 4, 6, 12]\nassert divisors(13) == [1, 13]",
        300,
    ),
    level(
        27,
        "Clean Palindrome",
        "Implement `is_clean_palindrome(text)`.\nIgnore spaces and case while checking palindrome.",
        "`text` is a string.",
        "Return `True` if palindrome, else `False`.",
        "`is_clean_palindrome('Never odd or even')` -> `True`",
        "- Remove spaces before comparing.",
        "def is_clean_palindrome(text):\n    pass\n",
        "assert is_clean_palindrome('Never odd or even') is True\nassert is_clean_palindrome('racecar') is True\nassert is_clean_palindrome('python') is False",
        300,
    ),
    level(
        28,
        "Prime Check",
        "Create `is_prime(n)` that checks primality.",
        "`n` is an integer.",
        "Return `True` if `n` is prime, else `False`.",
        "`is_prime(11)` -> `True`",
        "- Numbers less than 2 are not prime.",
        "def is_prime(n):\n    pass\n",
        "assert is_prime(2) is True\nassert is_prime(11) is True\nassert is_prime(1) is False\nassert is_prime(15) is False",
        300,
    ),
    level(
        29,
        "Nth Fibonacci",
        "Implement `fibonacci(n)` where `n` is zero-based.\n`fibonacci(0)=0`, `fibonacci(1)=1`.",
        "`n` is an integer where `n >= 0`.",
        "Return the nth Fibonacci number.",
        "`fibonacci(6)` -> `8`",
        "- Use iterative logic.",
        "def fibonacci(n):\n    pass\n",
        "assert fibonacci(0) == 0\nassert fibonacci(1) == 1\nassert fibonacci(6) == 8\nassert fibonacci(10) == 55",
        330,
    ),
    level(
        30,
        "Pair Sum Exists",
        "Write `has_pair_sum(nums, target)`.\nReturn whether any two different indices add up to `target`.",
        "`nums` is a list of integers.",
        "Return boolean.",
        "`has_pair_sum([1,4,6], 10)` -> `True`",
        "- Use each element at most once per pair.",
        "def has_pair_sum(nums, target):\n    pass\n",
        "assert has_pair_sum([1, 4, 6], 10) is True\nassert has_pair_sum([2, 7, 11, 15], 9) is True\nassert has_pair_sum([3, 3], 7) is False",
        330,
    ),
    # STAGE 4: FUNCTIONS & PATTERNS (31-40)
    level(
        31,
        "Operation Router",
        "Implement `operate(a, b, op)` for operators `+`, `-`, `*`, `/`.",
        "`a` and `b` are numbers, `op` is a string.",
        "Return computed numeric result.",
        "`operate(8, 2, '/')` -> `4`",
        "- Raise `ValueError` for unsupported operators.",
        "def operate(a, b, op):\n    pass\n",
        "assert operate(5, 3, '+') == 8\nassert operate(5, 3, '-') == 2\nassert operate(5, 3, '*') == 15\nassert operate(8, 2, '/') == 4\ntry:\n    operate(1, 2, '%')\n    raise AssertionError('Expected ValueError')\nexcept ValueError:\n    pass",
        330,
    ),
    level(
        32,
        "Safe Divide",
        "Create `safe_divide(a, b, default=None)`.\nReturn `a / b` unless `b == 0`, then return `default`.",
        "`a` and `b` are numbers.",
        "Return quotient or default value.",
        "`safe_divide(10, 0, -1)` -> `-1`",
        "- Do not raise division errors.",
        "def safe_divide(a, b, default=None):\n    pass\n",
        "assert safe_divide(10, 2) == 5\nassert safe_divide(10, 0) is None\nassert safe_divide(10, 0, -1) == -1",
        330,
    ),
    level(
        33,
        "Title Case Sentence",
        "Write `to_title_case(sentence)` that capitalizes each word.\nThe rest of each word should be lowercase.",
        "`sentence` is a string.",
        "Return transformed sentence.",
        "`to_title_case('heLLo woRLD')` -> `'Hello World'`",
        "- Words are separated by spaces.",
        "def to_title_case(sentence):\n    pass\n",
        "assert to_title_case('heLLo woRLD') == 'Hello World'\nassert to_title_case('python') == 'Python'\nassert to_title_case('') == ''",
        360,
    ),
    level(
        34,
        "Rotate Left",
        "Implement `rotate_left(items, k)` to rotate a list left by `k` steps.",
        "`items` is a list, `k` is an integer.",
        "Return a new rotated list.",
        "`rotate_left([1,2,3,4], 1)` -> `[2,3,4,1]`",
        "- Support `k` larger than list length.",
        "def rotate_left(items, k):\n    pass\n",
        "assert rotate_left([1, 2, 3, 4], 1) == [2, 3, 4, 1]\nassert rotate_left([1, 2, 3, 4], 5) == [2, 3, 4, 1]\nassert rotate_left([], 3) == []",
        360,
    ),
    level(
        35,
        "Chunk List",
        "Create `chunk_list(items, size)` that splits items into chunks of length `size`.",
        "`items` is a list and `size > 0`.",
        "Return list of chunk lists.",
        "`chunk_list([1,2,3,4,5],2)` -> `[[1,2],[3,4],[5]]`",
        "- Keep original order.",
        "def chunk_list(items, size):\n    pass\n",
        "assert chunk_list([1, 2, 3, 4, 5], 2) == [[1, 2], [3, 4], [5]]\nassert chunk_list([], 3) == []",
        360,
    ),
    level(
        36,
        "Running Total",
        "Implement `running_total(nums)`.\nEach result element should be the cumulative sum up to that index.",
        "`nums` is a list of integers.",
        "Return list of cumulative sums.",
        "`running_total([2,3,5])` -> `[2,5,10]`",
        "- Empty list returns empty list.",
        "def running_total(nums):\n    pass\n",
        "assert running_total([2, 3, 5]) == [2, 5, 10]\nassert running_total([]) == []\nassert running_total([1, -1, 4]) == [1, 0, 4]",
        390,
    ),
    level(
        37,
        "Word Frequencies",
        "Write `word_frequencies(text)` that counts words case-insensitively.",
        "`text` is a string with space-separated words.",
        "Return dictionary `{word: count}` in lowercase keys.",
        "`word_frequencies('Hi hi')` -> `{'hi': 2}`",
        "- Use whitespace splitting.",
        "def word_frequencies(text):\n    pass\n",
        "assert word_frequencies('Hi hi there') == {'hi': 2, 'there': 1}\nassert word_frequencies('') == {}",
        390,
    ),
    level(
        38,
        "Anagram Check",
        "Create `are_anagrams(a, b)`.\nIgnore spaces and case.",
        "`a` and `b` are strings.",
        "Return `True` if the cleaned strings are anagrams.",
        "`are_anagrams('Dormitory', 'Dirty room')` -> `True`",
        "- Compare character counts.",
        "def are_anagrams(a, b):\n    pass\n",
        "assert are_anagrams('Dormitory', 'Dirty room') is True\nassert are_anagrams('Listen', 'Silent') is True\nassert are_anagrams('Code', 'Coder') is False",
        390,
    ),
    level(
        39,
        "Transpose Matrix",
        "Implement `transpose(matrix)` for a rectangular matrix.",
        "`matrix` is a list of equal-length lists.",
        "Return transposed matrix.",
        "`transpose([[1,2,3],[4,5,6]])` -> `[[1,4],[2,5],[3,6]]`",
        "- Return empty list for empty input.",
        "def transpose(matrix):\n    pass\n",
        "assert transpose([[1, 2, 3], [4, 5, 6]]) == [[1, 4], [2, 5], [3, 6]]\nassert transpose([]) == []",
        420,
    ),
    level(
        40,
        "Merge Sorted Lists",
        "Write `merge_sorted(left, right)` that merges two already-sorted lists.",
        "`left` and `right` are sorted integer lists.",
        "Return one sorted list containing all values.",
        "`merge_sorted([1,3],[2,4])` -> `[1,2,3,4]`",
        "- Keep duplicates.",
        "def merge_sorted(left, right):\n    pass\n",
        "assert merge_sorted([1, 3], [2, 4]) == [1, 2, 3, 4]\nassert merge_sorted([], [1, 2]) == [1, 2]\nassert merge_sorted([1, 2], []) == [1, 2]",
        420,
    ),
    # STAGE 5: STANDARD LIBRARY (41-50)
    level(
        41,
        "Most Common Character",
        "Use `collections.Counter` in `most_common_char(text)` to find the most frequent non-space character.\nIf tied, return the lexicographically smallest character.",
        "`text` is a string.",
        "Return a single character. Return `None` if no non-space characters exist.",
        "`most_common_char('aab bb')` -> `'b'`",
        "- Ignore spaces.",
        "from collections import Counter\n\n\ndef most_common_char(text):\n    pass\n",
        "assert most_common_char('aab bb') == 'b'\nassert most_common_char('ccbb') == 'b'\nassert most_common_char('   ') is None",
        420,
    ),
    level(
        42,
        "Group By First Letter",
        "Using `collections.defaultdict`, implement `group_by_first_letter(words)`.\nGroup words by their lowercase first character.",
        "`words` is a list of non-empty strings.",
        "Return dictionary of `{first_letter: [words...]}` in original order.",
        "`group_by_first_letter(['Apple','ant'])` -> `{'a':['Apple','ant']}`",
        "- Keep input order within each group.",
        "from collections import defaultdict\n\n\ndef group_by_first_letter(words):\n    pass\n",
        "assert group_by_first_letter(['Apple', 'ant', 'Boat']) == {'a': ['Apple', 'ant'], 'b': ['Boat']}\nassert group_by_first_letter([]) == {}",
        420,
    ),
    level(
        43,
        "Rotate Queue",
        "Use `collections.deque` in `rotate_queue(items, steps)`.\nRotate right by `steps` and return a list.",
        "`items` is a list, `steps` is an integer.",
        "Return rotated list.",
        "`rotate_queue([1,2,3],1)` -> `[3,1,2]`",
        "- Handle empty list safely.",
        "from collections import deque\n\n\ndef rotate_queue(items, steps):\n    pass\n",
        "assert rotate_queue([1, 2, 3], 1) == [3, 1, 2]\nassert rotate_queue([1, 2, 3], 4) == [3, 1, 2]\nassert rotate_queue([], 2) == []",
        450,
    ),
    level(
        44,
        "GCD And LCM",
        "Using `math.gcd`, implement `gcd_lcm(a, b)` returning `(gcd, lcm)`.",
        "`a` and `b` are positive integers.",
        "Return tuple `(gcd, lcm)`.",
        "`gcd_lcm(12, 18)` -> `(6, 36)`",
        "- LCM formula: `(a*b)//gcd`.",
        "import math\n\n\ndef gcd_lcm(a, b):\n    pass\n",
        "assert gcd_lcm(12, 18) == (6, 36)\nassert gcd_lcm(7, 5) == (1, 35)",
        450,
    ),
    level(
        45,
        "Adjacent Sums",
        "Use `itertools.pairwise` to build `adjacent_sums(nums)`.\nReturn sums of each adjacent pair.",
        "`nums` is a list of integers.",
        "Return list of integers.",
        "`adjacent_sums([1,2,3,4])` -> `[3,5,7]`",
        "- For fewer than 2 items, return empty list.",
        "from itertools import pairwise\n\n\ndef adjacent_sums(nums):\n    pass\n",
        "assert adjacent_sums([1, 2, 3, 4]) == [3, 5, 7]\nassert adjacent_sums([5]) == []\nassert adjacent_sums([]) == []",
        450,
    ),
    level(
        46,
        "Mean And Median",
        "Use the `statistics` module to implement `mean_and_median(nums)`.",
        "`nums` is a non-empty list of numbers.",
        "Return `(mean, median)`.",
        "`mean_and_median([1,2,3])` -> `(2,2)`",
        "- Keep exact numeric results.",
        "import statistics\n\n\ndef mean_and_median(nums):\n    pass\n",
        "assert mean_and_median([1, 2, 3]) == (2, 2)\nassert mean_and_median([1, 2, 3, 4]) == (2.5, 2.5)",
        480,
    ),
    level(
        47,
        "Days Between Dates",
        "Using `datetime`, implement `days_between(start_date, end_date)`.\nDates are in `YYYY-MM-DD` format.",
        "`start_date` and `end_date` are date strings.",
        "Return absolute number of days between them.",
        "`days_between('2026-01-01', '2026-01-10')` -> `9`",
        "- Use calendar-accurate date math.",
        "from datetime import datetime\n\n\ndef days_between(start_date, end_date):\n    pass\n",
        "assert days_between('2026-01-01', '2026-01-10') == 9\nassert days_between('2024-02-28', '2024-03-01') == 2\nassert days_between('2026-01-10', '2026-01-01') == 9",
        480,
    ),
    level(
        48,
        "Sorted JSON Keys",
        "Using `json`, write `sorted_json_keys(raw_json)` for a top-level JSON object.",
        "`raw_json` is a JSON string representing an object.",
        "Return sorted list of top-level keys.",
        "`sorted_json_keys('{\"b\":2,\"a\":1}')` -> `['a','b']`",
        "- Keys should be returned in ascending order.",
        "import json\n\n\ndef sorted_json_keys(raw_json):\n    pass\n",
        "assert sorted_json_keys('{\"b\":2,\"a\":1}') == ['a', 'b']\nassert sorted_json_keys('{\"x\":1}') == ['x']",
        480,
    ),
    level(
        49,
        "Extract Integers",
        "Use `re` in `extract_integers(text)` to find all signed integers in order.",
        "`text` is a string.",
        "Return list of integers.",
        "`extract_integers('x=-3 y=20')` -> `[-3, 20]`",
        "- Include negative values.",
        "import re\n\n\ndef extract_integers(text):\n    pass\n",
        "assert extract_integers('x=-3 y=20') == [-3, 20]\nassert extract_integers('no numbers') == []\nassert extract_integers('7 8 -9') == [7, 8, -9]",
        540,
    ),
    level(
        50,
        "Product With Reduce",
        "Using `functools.reduce`, implement `product(nums)`.",
        "`nums` is a list of integers.",
        "Return the multiplicative product of all values.",
        "`product([2,3,4])` -> `24`",
        "- Empty list should return `1`.",
        "from functools import reduce\n\n\ndef product(nums):\n    pass\n",
        "assert product([2, 3, 4]) == 24\nassert product([5]) == 5\nassert product([]) == 1",
        540,
    ),
    # STAGE 6: OOP MASTERY (51-60)
    level(
        51,
        "Click Counter Class",
        "Create class `ClickCounter` with:\n- `value` attribute (starts at 0)\n- `increment(step=1)` method\n- `reset()` method",
        "Instantiate `ClickCounter()` with no args.",
        "`increment` returns new value. `reset` sets value back to 0.",
        "`c.increment()` -> `1`",
        "- Keep state in `self.value`.",
        "class ClickCounter:\n    pass\n",
        "c = ClickCounter()\nassert c.value == 0\nassert c.increment() == 1\nassert c.increment(4) == 5\nc.reset()\nassert c.value == 0",
        540,
    ),
    level(
        52,
        "Bank Account",
        "Implement class `BankAccount` with starting `balance=0`.\nMethods:\n- `deposit(amount)` adds and returns new balance\n- `withdraw(amount)` subtracts when possible and returns `True`, else `False`",
        "`BankAccount(balance=0)`",
        "Maintain valid account balance.",
        "`withdraw` should fail when amount exceeds balance.",
        "- Balance must not go below 0.",
        "class BankAccount:\n    def __init__(self, balance=0):\n        self.balance = balance\n",
        "acct = BankAccount(100)\nassert acct.deposit(50) == 150\nassert acct.withdraw(25) is True\nassert acct.balance == 125\nassert acct.withdraw(500) is False\nassert acct.balance == 125",
        540,
    ),
    level(
        53,
        "Student Counter",
        'Create class `Student` with class variable `student_count`.\nIncrease it every time a new student is created.\nAlso implement `label()` returning `"<name> (Grade <grade>)"`.',
        "Constructor: `Student(name, grade)`.",
        "Track instances and return formatted labels.",
        "`Student('Kira', 10).label()` -> `'Kira (Grade 10)'`",
        "- `student_count` belongs to the class, not instances.",
        "class Student:\n    pass\n",
        "Student.student_count = 0\ns1 = Student('Kira', 10)\ns2 = Student('Finn', 11)\nassert Student.student_count == 2\nassert s1.label() == 'Kira (Grade 10)'\nassert s2.label() == 'Finn (Grade 11)'",
        570,
    ),
    level(
        54,
        "Rectangle Class",
        "Build class `Rectangle(width, height)` with methods `area()` and `perimeter()`.",
        "Constructor takes `width` and `height`.",
        "Return computed geometry values.",
        "`Rectangle(3,4).area()` -> `12`",
        "- Use instance attributes.",
        "class Rectangle:\n    pass\n",
        "r = Rectangle(3, 4)\nassert r.area() == 12\nassert r.perimeter() == 14",
        570,
    ),
    level(
        55,
        "Inheritance Override",
        "Create base class `Vehicle` with method `move()` returning `'Vehicle moving'`.\nCreate class `Car(Vehicle)` overriding `move()` to return `'Car driving'`.",
        "No constructor arguments required.",
        "Demonstrate method overriding.",
        "`Car().move()` -> `'Car driving'`",
        "- `Car` must inherit from `Vehicle`.",
        "class Vehicle:\n    pass\n\n\nclass Car(Vehicle):\n    pass\n",
        "v = Vehicle()\nc = Car()\nassert v.move() == 'Vehicle moving'\nassert c.move() == 'Car driving'\nassert isinstance(c, Vehicle)",
        570,
    ),
    level(
        56,
        "Stack Class",
        "Implement class `Stack` with methods:\n- `push(item)`\n- `pop()` (return `None` if empty)\n- `peek()` (return top or `None`)\n- `is_empty()`",
        "Use internal list storage.",
        "Return correct stack behavior (LIFO).",
        "`push(1), push(2), pop()` -> `2`",
        "- Do not raise on empty pop/peek.",
        "class Stack:\n    pass\n",
        "s = Stack()\nassert s.is_empty() is True\ns.push(10)\ns.push(20)\nassert s.peek() == 20\nassert s.pop() == 20\nassert s.pop() == 10\nassert s.pop() is None\nassert s.is_empty() is True",
        600,
    ),
    level(
        57,
        "Temperature Model",
        "Create class `Temperature` storing Celsius in `self.celsius`.\nMethods:\n- `to_fahrenheit()`\n- classmethod `from_fahrenheit(f)` returning a `Temperature` instance",
        "Constructor: `Temperature(celsius)`.",
        "Convert between scales accurately.",
        "`Temperature.from_fahrenheit(212).celsius` -> `100`",
        "- Keep formulas consistent.",
        "class Temperature:\n    pass\n",
        "t = Temperature(100)\nassert t.to_fahrenheit() == 212\ncold = Temperature.from_fahrenheit(32)\nassert isinstance(cold, Temperature)\nassert cold.celsius == 0",
        600,
    ),
    level(
        58,
        "Todo List",
        "Implement class `TodoList` managing internal task dictionaries with shape `{'title': str, 'done': bool}`.\nMethods:\n- `add_task(title)`\n- `complete_task(index)`\n- `pending_tasks()` returns titles not done",
        "Use zero-based indices.",
        "Return/update todo state correctly.",
        "After completing one task, `pending_tasks()` excludes it.",
        "- Ignore invalid complete indices (do nothing).",
        "class TodoList:\n    pass\n",
        "todo = TodoList()\ntodo.add_task('Read')\ntodo.add_task('Practice')\nassert todo.pending_tasks() == ['Read', 'Practice']\ntodo.complete_task(0)\nassert todo.pending_tasks() == ['Practice']\ntodo.complete_task(99)\nassert todo.pending_tasks() == ['Practice']",
        600,
    ),
    level(
        59,
        "Inventory Manager",
        "Create class `Inventory` with stock per item name.\nMethods:\n- `add(item, qty)`\n- `remove(item, qty)` (do not go below 0)\n- `quantity(item)`",
        "Quantities are non-negative integers.",
        "Maintain stock levels by item name.",
        "Removing more than available should clamp to 0.",
        "- Unknown items have quantity 0.",
        "class Inventory:\n    pass\n",
        "inv = Inventory()\ninv.add('pen', 10)\ninv.remove('pen', 3)\nassert inv.quantity('pen') == 7\ninv.remove('pen', 99)\nassert inv.quantity('pen') == 0\nassert inv.quantity('book') == 0",
        600,
    ),
    level(
        60,
        "Grade Book",
        "Implement class `GradeBook`.\nMethods:\n- `add_score(student, score)`\n- `student_average(student)` returns average or `None`\n- `class_average()` returns overall average or `None`",
        "`student` is a string and `score` is numeric.",
        "Compute per-student and overall averages.",
        "If no scores exist, average methods return `None`.",
        "- Use floating-point division.",
        "class GradeBook:\n    pass\n",
        "g = GradeBook()\nassert g.student_average('Kira') is None\nassert g.class_average() is None\ng.add_score('Kira', 80)\ng.add_score('Kira', 90)\ng.add_score('Finn', 70)\nassert g.student_average('Kira') == 85\nassert g.student_average('Finn') == 70\nassert g.class_average() == 80",
        600,
    ),
]
