# Generated by Django 6.0.1 on 2026-01-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0004_userprofile_referral_code_userprofile_referred_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="github_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="leetcode_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
