# Generated by Django 6.0.1 on 2026-01-17 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_userprofile_github_username_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userfollow",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="userfollow",
            name="authenticat_followe_e90fa8_idx",
        ),
        migrations.RemoveField(
            model_name="userfollow",
            name="follower",
        ),
        migrations.RemoveField(
            model_name="userfollow",
            name="following",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
        migrations.DeleteModel(
            name="UserFollow",
        ),
    ]
