# Generated by Django 5.0.9 on 2026-02-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
