# Generated by Django 5.0.9 on 2026-04-26 10:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
                ),
                ("issued_date", models.DateTimeField(auto_now_add=True)),
                (
                    "certificate_image",
                    models.ImageField(blank=True, null=True, upload_to="certificates/"),
                ),
                ("is_valid", models.BooleanField(default=True)),
                (
                    "completion_count",
                    models.IntegerField(help_text="Number of challenges completed when certificate was issued"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "challenges_usercertificate",
                "ordering": ["-issued_date"],
            },
        ),
        migrations.CreateModel(
            name="CertificateVerificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verified_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("referer", models.URLField(blank=True, null=True)),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_logs",
                        to="certificates.usercertificate",
                    ),
                ),
            ],
            options={
                "ordering": ["-verified_at"],
            },
        ),
    ]
