# Generated by Django 5.0.9 on 2026-04-26 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("cost", models.IntegerField(help_text="Cost in XP")),
                (
                    "icon_name",
                    models.CharField(
                        help_text="Lucide icon name or image path identifier",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("THEME", "Theme"),
                            ("FONT", "Font"),
                            ("EFFECT", "Effect"),
                            ("VICTORY", "Victory"),
                        ],
                        default="ITEM",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        help_text="Path to image in public folder (e.g. /store/dracula.png)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "item_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON data for functional items (e.g., theme_key)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="store.storeitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-purchased_at"],
                "indexes": [
                    models.Index(fields=["user", "item"], name="store_purch_user_id_3ccbca_idx"),
                    models.Index(
                        fields=["user", "-purchased_at"],
                        name="store_purch_user_id_babd9e_idx",
                    ),
                ],
                "unique_together": {("user", "item")},
            },
        ),
    ]
