# Generated by Django 6.0.1 on 2026-01-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_storeitem_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("ITEM", "Item"),
                    ("THEME", "Theme"),
                    ("BADGE", "Badge"),
                    ("BOOSTER", "Booster"),
                    ("FONT", "Font"),
                    ("EFFECT", "Cursor Effect"),
                    ("VICTORY", "Victory Animation"),
                ],
                default="ITEM",
                max_length=20,
            ),
        ),
    ]
