# Generated by Django 5.0.9 on 2026-03-22 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_add_purchase_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="purchase",
            new_name="store_purch_user_id_3ccbca_idx",
            old_name="store_purch_user_id_145506_idx",
        ),
        migrations.RenameIndex(
            model_name="purchase",
            new_name="store_purch_user_id_babd9e_idx",
            old_name="store_purch_user_id_853503_idx",
        ),
    ]
