# Generated by Django 5.0.9 on 2026-03-22 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_add_notification_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="fcmtoken",
            new_name="notificatio_user_id_77e5df_idx",
            old_name="notifications_user_id_2085dc_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_a972ce_idx",
            old_name="notificatio_recipie_452e95_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_684eac_idx",
            old_name="notificatio_recipie_26c92a_idx",
        ),
    ]
