namespace: clashcode

resources:
  - ../../base
  - ./ingress.yaml
  - ./secrets.yaml

images:
  - name: core
    newName: 317451122305.dkr.ecr.ap-south-1.amazonaws.com/clashcode-core
    newTag: prod
  - name: chat
    newName: 317451122305.dkr.ecr.ap-south-1.amazonaws.com/clashcode-chat
    newTag: prod
  - name: ai
    newName: 317451122305.dkr.ecr.ap-south-1.amazonaws.com/clashcode-ai
    newTag: prod
  - name: analytics
    newName: 317451122305.dkr.ecr.ap-south-1.amazonaws.com/clashcode-analytics
    newTag: prod
  - name: executor
    newName: 317451122305.dkr.ecr.ap-south-1.amazonaws.com/clashcode-executor
    newTag: prod

labels:
  - pairs:
      environment: production
      project: clashcode
    includeSelectors: true
