# Generated by Django 6.0.1 on 2026-01-15 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in_date", models.DateField(auto_now_add=True)),
                ("streak_day", models.IntegerField(default=1)),
                ("xp_earned", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_ins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Check-In",
                "verbose_name_plural": "Daily Check-Ins",
                "ordering": ["-check_in_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-check_in_date"],
                        name="rewards_dai_user_id_252ab0_idx",
                    )
                ],
                "unique_together": {("user", "check_in_date")},
            },
        ),
    ]
