apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  DB_HOST: "aws-1-ap-south-1.pooler.supabase.com"
  DB_PORT: "6543"
  DB_NAME: "postgres"
  DB_USER: "postgres.tjbxnwvkhgggtrbsnysp"
  DB_PASSWORD: "Jithinlal#44"
  DB_SSLMODE: "require"
  REDIS_URL: "redis://PLACEHOLDER_REDIS_ENDPOINT:6379/0"
  DYNAMODB_TABLE: "clashcode-chat-messages"
