# Generated by Django 5.0.9 on 2026-04-25 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="XPTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Amount of XP (positive for gain, negative for spend)"
                    ),
                ),
                (
                    "balance_after",
                    models.IntegerField(help_text="XP balance after this transaction"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("check_in", "Daily Check-in"),
                            ("purchase", "Store Purchase"),
                            ("referral", "Referral Reward"),
                            ("challenge", "Challenge Completion"),
                            ("admin", "Admin Adjustment"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xp_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="xpoint_xptr_user_id_5a9a24_idx",
                    ),
                    models.Index(
                        fields=["source"], name="xpoint_xptr_source_499f39_idx"
                    ),
                ],
            },
        ),
    ]
